-- MySQL Script generated by MySQL Workbench
-- Thu Sep 15 17:01:34 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Admin` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Admin` (
  `Nome` VARCHAR(250) NOT NULL,
  `Senha` VARCHAR(100) NOT NULL,
  `Superadmin` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`Nome`),
  INDEX `fk_Admin_Admin1_idx` (`Superadmin` ASC) VISIBLE,
  CONSTRAINT `fk_Admin_Admin1`
    FOREIGN KEY (`Superadmin`)
    REFERENCES `mydb`.`Admin` (`Nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Categoria` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Categoria` (
  `Id` CHAR(8) NOT NULL,
  `Nome` VARCHAR(250) NOT NULL,
  `Usuário` VARCHAR(250) NOT NULL,
  `Admin` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Categoria_Usuário1_idx` (`Usuário` ASC) VISIBLE,
  INDEX `fk_Categoria_Admin1_idx` (`Admin` ASC) VISIBLE,
  CONSTRAINT `fk_Categoria_Usuário1`
    FOREIGN KEY (`Usuário`)
    REFERENCES `mydb`.`Usuário` (`Email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Categoria_Admin1`
    FOREIGN KEY (`Admin`)
    REFERENCES `mydb`.`Admin` (`Nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Endereço`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Endereço` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Endereço` (
  `Usuário` VARCHAR(250) NOT NULL,
  `CEP` CHAR(8) NOT NULL,
  `Rua` VARCHAR(50) NOT NULL,
  `Cidade` VARCHAR(45) NOT NULL,
  `Número` INT NOT NULL,
  `Complemento` VARCHAR(45) NULL,
  `Admin` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`CEP`, `Usuário`),
  INDEX `fk_Endereço_Usuário_idx` (`Usuário` ASC) VISIBLE,
  INDEX `fk_Endereço_Admin1_idx` (`Admin` ASC) VISIBLE,
  CONSTRAINT `fk_Endereço_Usuário`
    FOREIGN KEY (`Usuário`)
    REFERENCES `mydb`.`Usuário` (`Email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Endereço_Admin1`
    FOREIGN KEY (`Admin`)
    REFERENCES `mydb`.`Admin` (`Nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tutorial`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tutorial` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Tutorial` (
  `Id` CHAR(8) NOT NULL,
  `Título` VARCHAR(45) NOT NULL,
  `Texto` VARCHAR(300) NOT NULL,
  `URL` VARCHAR(250) NOT NULL,
  `Categoria` CHAR(8) NOT NULL,
  `Admin` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) VISIBLE,
  INDEX `fk_Tutorial_Categoria1_idx` (`Categoria` ASC) VISIBLE,
  INDEX `fk_Tutorial_Admin1_idx` (`Admin` ASC) VISIBLE,
  CONSTRAINT `fk_Tutorial_Categoria1`
    FOREIGN KEY (`Categoria`)
    REFERENCES `mydb`.`Categoria` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tutorial_Admin1`
    FOREIGN KEY (`Admin`)
    REFERENCES `mydb`.`Admin` (`Nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuário`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuário` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuário` (
  `Email` VARCHAR(250) NOT NULL,
  `Nome` VARCHAR(250) NOT NULL,
  `Telefone` CHAR(11) NOT NULL,
  `Senha` VARCHAR(100) NOT NULL,
  `Admin` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`Email`),
  UNIQUE INDEX `EmailUsuário_UNIQUE` (`Email` ASC) VISIBLE,
  UNIQUE INDEX `Telefone_UNIQUE` (`Telefone` ASC) VISIBLE,
  INDEX `fk_Usuário_Admin1_idx` (`Admin` ASC) VISIBLE,
  CONSTRAINT `fk_Usuário_Admin1`
    FOREIGN KEY (`Admin`)
    REFERENCES `mydb`.`Admin` (`Nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
